---
- src: https://github.com/mtbvang/ansible-role-devtools
  name: devtools
  version: v1.1.3
- src: https://github.com/mtbvang/ansible-role-openshift_client.git
  name: openshift_client
  version: v0.1.0
- src: https://github.com/mtbvang/ansible-role-terraform
  name: terraform
  version: 'v0.1.0'
- src: https://github.com/mtbvang/ansible-role-awscli
  name: awscli
  
  